### ISSUE TITLE
Grids with columns of the same name (from different entities) require a label

### ISSUE THREAD

**Issue by rsyring** [level12/webgrid#122]
I have the following grid:

```python
class Product(Grid):
    webgrid.Column('Code', ents.Product.code, filters.TextFilter)
    webgrid.Column('Per Case', ents.Product.per_case, filters.IntFilter)
    webgrid.Column('Category', ents.ProductCat.name.label('pc_name'))
    webgrid.Column('Department', ents.Department.name)
```
Without the `label` on `ProductCat.name`, the grid renders the department's name in the category column.  I feel like that shouldn't be needed.

**Comment by calebsyring** [comment]
I've run into this before. I believe it's because the default name of the webgrid column is the sqlalchemy column name, so if you have two columns that reflect name columns from two different entities and don't specify a different label for one of them, you're going to end up with two webgrid columns named "name" as well, which leads to issues. At the very least, I would think there should be an exception raised saying that we have two webgrid columns with the same name and need to change one of them.

**Comment by guruofgentoo** [comment]
Caleb's analysis is correct, and it's a long-standing limitation. I think back in the SQLAlchemy core days, we were able to reference into the record with the column expression, but with ORM queries that is not supported.

That said, it's not developer-friendly and requires too much knowledge of the grid internals. There are ways to walk around this:
- for most queries, we are building the columns list internally, so we know the order of columns in the result. We can index that and cross-reference the field name at that position in the record with the column's query key
- queries that are modified such that index/name don't match, can fall back to the attribute reference. If the query is getting that level of modification, we're doing something more advanced anyway.
- that leaves the issue that the grid assumes column "key" names will be unique, because they are used for reference into the various dicts of columns, filtered columns, etc.
  - we should handle this such that the column's query key (i.e. the field name in the result set) and the grid key (i.e. reference for filters in URL, etc.) may be different. The grid can then handle conflicts internally when the columns are created for the grid instance.
