### ISSUE TITLE
Move Add Filter to top of form (right of Search?)

### ISSUE THREAD

**Issue by rsyring** [level12/webgrid#132]
Seems like we could easily move the "Add filter" label & drop-down to the right of the Search text box.  Making better use of horizontal space available and keeping the default look shorter:

![webgrid](https://user-images.githubusercontent.com/109467/95787620-e5d5d500-0ca7-11eb-83a9-4c9ad5552845.png)

**Comment by matthiaswh** [comment]
For context, there was some previous discussion of the layout on https://github.com/level12/webgrid/issues/73

**Comment by guruofgentoo** [comment]
My concern here is that (in master anyway) the current placement of Add Filter and the resulting filters allows for less mouse movement. Select a filter, and it will pop up right where the mouse is.

**Comment by matthiaswh** [comment]
Perhaps it's just me, but after clicking which filter to add, I inevitably always click the _Add Filter_ dropdown again rather than the dropdown for the filter I just added. 

![Kazam-screencast-00007](https://user-images.githubusercontent.com/476857/95855708-d2b61a00-0d26-11eb-893c-4f2a82833bae.gif)

This is how Metabase does it, which I find very intuitive and natural. Of course, it _is_ a lot more mouse movement.

![Kazam-screencast-00005](https://user-images.githubusercontent.com/476857/95855740-e1043600-0d26-11eb-9af4-738c45b8c2de.gif)

**Comment by guruofgentoo** [comment]
@matthiaswh try what's in master now. Op is selected automatically, and focus given to the value input.

**Comment by matthiaswh** [comment]
> @matthiaswh try what's in master now. Op is selected automatically, and focus given to the value input.

I missed that update. This is a _huge_ improvement already.

**Comment by rsyring** [comment]
> My concern here is that (in master anyway) the current placement of Add Filter and the resulting filters allows for less mouse movement. Select a filter, and it will pop up right where the mouse is.

I think that's only true if you add a filter, set the value, add another filter, set a value, etc.  If you add the filters all at once, then it's relatively small mouse movement.  

I'd like to make the change and see how it works in practice.  My guess is, it's not a big UX con and I like taking up less page realestate when not used.  

I guess, the other option would be to move the search over to the right and move Add Filter to the top.  Could eventually add filters at the top instead of bottom of the stack, but I'm not sure that necessary.
